# Generated by Django 2.1.7 on 2019-02-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190217_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-create_time'], 'verbose_name_plural': 'weathers'},
        ),
    ]
